// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/admin/_middleware.ts";
import * as $5 from "./routes/admin/members.tsx";
import * as $6 from "./routes/api/admin/_middleware.ts";
import * as $7 from "./routes/api/admin/auth-token.ts";
import * as $8 from "./routes/api/member.ts";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/whoami.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/admin/_middleware.ts": $4,
    "./routes/admin/members.tsx": $5,
    "./routes/api/admin/_middleware.ts": $6,
    "./routes/api/admin/auth-token.ts": $7,
    "./routes/api/member.ts": $8,
    "./routes/index.tsx": $9,
    "./routes/whoami.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
